# zhiyuan/filter/retriever_filter.py
# PURPOSE: Use trained DPR retriever to score and filter weak pairs
# This REPLACES the BM25 filter for iterative rounds

from sentence_transformers import SentenceTransformer, util
import json
import os
import torch
import argparse

def load_weak_pairs(weak_data_path):
    """
    Load weak query-document pairs generated by SPTAR's soft prompt augmentor.
    Handles both jsonl format and json format.
    """
    pairs = []
    with open(weak_data_path, 'r') as f:
        for line in f:
            line = line.strip()
            if line:
                pairs.append(json.loads(line))
    print(f"Loaded {len(pairs)} weak pairs from {weak_data_path}")
    return pairs

def load_corpus(corpus_path):
    """
    Load all documents from corpus_filtered.jsonl
    Same file used by bm25anserini_split.py
    """
    documents = []
    doc_ids = []
    with open(corpus_path, 'r') as f:
        for line in f:
            line = line.strip()
            if line:
                doc = json.loads(line)
                # handle both 'text' and 'contents' field names
                text = doc.get('text', doc.get('contents', ''))
                doc_id = doc.get('_id', doc.get('id', ''))
                documents.append(text)
                doc_ids.append(doc_id)
    print(f"Loaded {len(documents)} documents from corpus")
    return documents, doc_ids

def encode_corpus(retriever, documents, batch_size=128):
    """
    Encode all corpus documents into dense vectors using trained retriever.
    Only done ONCE per round — reused for all 100K queries.
    """
    print(f"Encoding {len(documents)} corpus documents...")
    doc_embeddings = retriever.encode(
        documents,
        batch_size=batch_size,
        show_progress_bar=True,
        convert_to_tensor=True,
        normalize_embeddings=True  # for cosine similarity
    )
    return doc_embeddings

def compute_quality_scores(retriever, weak_pairs, doc_embeddings, 
                           doc_ids, top_k=50, batch_size=128):
    """
    CORE FUNCTION — scores every weak pair using the trained retriever.
    
    For each weak query:
    1. Encode it with the retriever
    2. Find where its target document ranks in retrieval results
    3. Assign soft quality score based on rank
    
    This is fundamentally different from BM25 filtering because:
    - Uses DENSE retrieval not lexical matching
    - Gives SOFT scores not binary pass/fail
    - Uses the SAME model that will train on this data
    """
    
    # get doc_id field name — could be different in your data
    sample = weak_pairs[0]
    if 'doc_id' in sample:
        doc_id_field = 'doc_id'
    elif 'corpus_id' in sample:
        doc_id_field = 'corpus_id'
    elif '_id' in sample:
        doc_id_field = '_id'
    else:
        # print all keys to help debug
        print(f"WARNING: unknown doc_id field. Keys found: {sample.keys()}")
        doc_id_field = list(sample.keys())[1]  # guess second field
    
    print(f"Using '{doc_id_field}' as document ID field")
    
    # get query field name
    if 'query' in sample:
        query_field = 'query'
    elif 'question' in sample:
        query_field = 'question'
    else:
        query_field = list(sample.keys())[0]
    
    print(f"Using '{query_field}' as query field")
    
    # encode all queries in batches
    queries = [pair[query_field] for pair in weak_pairs]
    print(f"Encoding {len(queries)} weak queries...")
    query_embeddings = retriever.encode(
        queries,
        batch_size=batch_size,
        show_progress_bar=True,
        convert_to_tensor=True,
        normalize_embeddings=True
    )
    
    # build doc_id to index mapping for fast lookup
    doc_id_to_idx = {doc_id: idx for idx, doc_id in enumerate(doc_ids)}
    
    # score every pair
    scored_pairs = []
    print("Computing retrieval scores for all weak pairs...")
    
    for i, pair in enumerate(weak_pairs):
        query_emb = query_embeddings[i].unsqueeze(0)  # [1, dim]
        target_doc_id = str(pair[doc_id_field])
        
        # compute similarity with ALL corpus documents
        # dot product since embeddings are normalized
        similarities = torch.mm(query_emb, doc_embeddings.T)[0]  # [num_docs]
        
        # get top_k results
        top_k_scores, top_k_indices = torch.topk(similarities, 
                                                   min(top_k, len(doc_ids)))
        top_k_doc_ids = [str(doc_ids[idx.item()]) for idx in top_k_indices]
        
        # find rank of target document
        if target_doc_id in top_k_doc_ids:
            rank = top_k_doc_ids.index(target_doc_id) + 1  # 1-indexed
        else:
            rank = None  # not found in top_k
        
        # SOFT QUALITY SCORING
        # better than BM25's binary 0/1
        if rank is None:
            quality_score = 0.0
        elif rank <= 10:
            quality_score = 1.0    # excellent — retriever finds it easily
        elif rank <= 20:
            quality_score = 0.8    # very good
        elif rank <= 30:
            quality_score = 0.6    # good
        elif rank <= 50:
            quality_score = 0.3    # marginal
        else:
            quality_score = 0.0    # bad
        
        scored_pairs.append({
            **pair,
            'rank': rank if rank else -1,
            'quality_score': quality_score
        })
        
        # progress update every 10k pairs
        if (i + 1) % 10000 == 0:
            print(f"  Scored {i+1}/{len(weak_pairs)} pairs...")
    
    return scored_pairs

def filter_by_quality(scored_pairs, threshold=0.3, top_n=None):
    """
    Two filtering modes:
    
    Mode 1 (threshold): keep all pairs with quality_score >= threshold
    Mode 2 (top_n): keep top N pairs ranked by quality_score
    
    Use top_n for ablation experiments in your paper
    e.g. top_n=10000, 30000, 50000 to show effect of data size
    """
    if top_n is not None:
        sorted_pairs = sorted(
            scored_pairs,
            key=lambda x: x['quality_score'],
            reverse=True
        )
        filtered = sorted_pairs[:top_n]
        print(f"Top-N mode: kept {len(filtered)} pairs (top {top_n})")
    else:
        filtered = [p for p in scored_pairs 
                   if p['quality_score'] >= threshold]
        print(f"Threshold mode: kept {len(filtered)} pairs "
              f"(threshold={threshold})")
    
    return filtered

def print_statistics(weak_pairs, scored_pairs, filtered_pairs):
    """Print useful statistics for your paper's analysis section"""
    total = len(weak_pairs)
    scored_nonzero = sum(1 for p in scored_pairs if p['quality_score'] > 0)
    kept = len(filtered_pairs)
    
    print("\n=== Filtering Statistics ===")
    print(f"Total weak pairs:        {total}")
    print(f"Pairs with rank found:   {scored_nonzero} "
          f"({100*scored_nonzero/total:.1f}%)")
    print(f"Pairs kept after filter: {kept} "
          f"({100*kept/total:.1f}%)")
    
    # quality score distribution
    scores = [p['quality_score'] for p in scored_pairs]
    print(f"\nQuality score distribution:")
    print(f"  Score = 1.0 (rank 1-10):  "
          f"{sum(1 for s in scores if s == 1.0)}")
    print(f"  Score = 0.8 (rank 11-20): "
          f"{sum(1 for s in scores if s == 0.8)}")
    print(f"  Score = 0.6 (rank 21-30): "
          f"{sum(1 for s in scores if s == 0.6)}")
    print(f"  Score = 0.3 (rank 31-50): "
          f"{sum(1 for s in scores if s == 0.3)}")
    print(f"  Score = 0.0 (not found):  "
          f"{sum(1 for s in scores if s == 0.0)}")
    print("============================\n")

def save_filtered_pairs(filtered_pairs, output_path):
    """Save in same jsonl format as original SPTAR weak data"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        for pair in filtered_pairs:
            f.write(json.dumps(pair) + '\n')
    print(f"Saved {len(filtered_pairs)} filtered pairs → {output_path}")

def run_retriever_filter(model_path, weak_data_path, corpus_path,
                         output_path, top_k=50, threshold=0.3, 
                         top_n=None, batch_size=128):
    """
    Main pipeline function.
    Call this from dpr_eval.py for each iterative round.
    """
    # load trained retriever
    print(f"Loading retriever from {model_path}...")
    retriever = SentenceTransformer(model_path)
    
    # load corpus and encode
    documents, doc_ids = load_corpus(corpus_path)
    doc_embeddings = encode_corpus(retriever, documents, batch_size)
    
    # load weak pairs
    weak_pairs = load_weak_pairs(weak_data_path)
    
    # score all pairs
    scored_pairs = compute_quality_scores(
        retriever, weak_pairs, doc_embeddings, doc_ids, top_k, batch_size
    )
    
    # filter
    filtered_pairs = filter_by_quality(scored_pairs, threshold, top_n)
    
    # print stats (useful for paper)
    print_statistics(weak_pairs, scored_pairs, filtered_pairs)
    
    # save
    save_filtered_pairs(filtered_pairs, output_path)
    
    return filtered_pairs, scored_pairs  # return both for analysis

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description='Retriever-guided weak data filtering'
    )
    parser.add_argument('--model_path', type=str, required=True,
                        help='Path to trained SPTAR DPR/SentenceTransformer model')
    parser.add_argument('--weak_data_path', type=str, required=True,
                        help='Path to raw unfiltered 100K weak pairs (.jsonl)')
    parser.add_argument('--corpus_path', type=str, required=True,
                        help='Path to corpus_filtered.jsonl')
    parser.add_argument('--output_path', type=str, required=True,
                        help='Where to save filtered pairs')
    parser.add_argument('--top_k', type=int, default=50,
                        help='Retrieval depth for scoring')
    parser.add_argument('--threshold', type=float, default=0.3,
                        help='Quality score threshold')
    parser.add_argument('--top_n', type=int, default=None,
                        help='Keep top N pairs (overrides threshold)')
    parser.add_argument('--batch_size', type=int, default=128)
    parser.add_argument('--round', type=int, default=1,
                        help='Iteration round number (for logging)')
    args = parser.parse_args()
    
    print(f"\n=== Retriever Filter — Round {args.round} ===")
    run_retriever_filter(
        model_path=args.model_path,
        weak_data_path=args.weak_data_path,
        corpus_path=args.corpus_path,
        output_path=args.output_path,
        top_k=args.top_k,
        threshold=args.threshold,
        top_n=args.top_n,
        batch_size=args.batch_size
    )
